---
- name: Ensure config desination directory exists
  file:
    path: /tmp/nginx/conf.d
    state: directory
    mode: '0644'

- name: Generate Nginx configuration file
  template:
    src: ../template/nginx.tmpl
    dest: /tmp/nginx/conf.d/default.conf

- name: Pull Nginx Docker image
  community.docker.docker_image:
    name: nginx
    tag: latest
    source: pull

- name: Start Nginx Docker container
  community.docker.docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    volumes:
      - /tmp/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    published_ports:
      - "80:80"