name: CI/CD Build And Deploy Image

on:
  push:
    branches: 
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Images
      run: |
        docker build -t ghcr.io/brozekm/dce_backend:latest -f ./backend/Dockerfile ./backend

    - name: Push Images
      run: |
        docker push ghcr.io/brozekm/dce_backend:latest
