name: CI/CD Build And Deploy Image

on:
  push:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Images
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/dce_backend:latest -f ./backend/Dockerfile ./backend

    - name: Push Images
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/dce_backend:latest
